---
title: "how_many_bioreactors_in_ag"
author: "sarah_kinz"
date: "5/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Loading packages ###
# install.packages("devtools")
# devtools::install_github("ropensci/FedData")
library(FedData)
library(rasterVis)
library(raster)
library(sp)
library(rgdal)
library(reshape2)
library(treemapify)
library(ggplot2)
library(kableExtra)
library(scales)
library(tidyverse)
library(sf)
library(dplyr)
library(spData)
library(tmap)
library(rgdal)
library(geojsonio)
library(leaflet)
library(data.table)
library(rgdal)
library(sp)
library(RColorBrewer)
library(rgeos) #for simplification
library(sf)
library(jsonlite)
library(RJSONIO)
# remotes::install_github("r-spatial/mapview")
library(mapview)



```


```{r}

### Creating Template ###

watersheds <- st_read("data_clean_up/Chesapeake_Bay_Watershed_Boundary/Chesapeake_Bay_Watershed_Boundary.shp")

watersheds<-st_transform(watersheds, crs = 4326)

### Reading in NLCD ### 

nlcd<-get_nlcd(watersheds, label='CBW')

class(nlcd)

### Reading in bioreactor data ###

bio_data<-read_csv("data_clean_up/all_data.csv")

class(bio_data)

spring_location<- bio_data%>%select(lon, lat)

# coordinates(spring_location) <- ~lon+lat

spring_location<- st_as_sf(bio_data, coords = c("lat","lon"), crs = 4326 )

spring_location<-as(spring_location, Class= "Spatial")

class(spring_location)


### Extracting Raster Values ### 

landuse<- raster::extract(nlcd, spring_location, df=TRUE)


### Connecting it with names ### 

unique(landuse$NLCD_2019_Land_Cover)

legend<-pal_nlcd()

landuse_combo<- full_join(landuse, legend, by = c("CBW_NLCD_Land_Cover_2019" = "ID"))

### Summarizing ###

landuse_table<-landuse_combo %>% group_by(Class)%>%summarize(group=n())


### 26 % of the 2950 known springs are in ag ###

### calculating percentage table ### 

landuse_percentage<- landuse_table %>% filter(group >= 2) %>% mutate(
  percentage = group/2950*100
)



```

### Determing landuse for my broad data
```{r}

```

